//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDIViewer.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA*00*DEIDENT   *00*          *ZZ*RYCANSENDER1234*ZZ*RYCANRECEIVER12*090604*0000*U*00305*000000001*0*P*&gt;~
        ///GS*HP*RYCANSENDER1234*RYCANRECEIVER12*090604*0000*1074*X*003051~
        ///ST*835*2074~
        ///BPR*I*3069.21*C*NON************090604~
        ///TRN*1*EFT342498620*1411293970~
        ///DTM*405*090604***20~
        ///N1*PR*WISCONSIN PHYSICIANS SERVICE INS. CORP.~
        ///N3*1234 PAYER ROAD*PO BOX 123~
        ///N4*SOMEWHERE*MN*12345~
        ///REF*2U*00954~
        ///N1*PE*FACILITY XYZ*XX*9999999999~
        ///N3*4321 HOSPITAL ROAD*PO BOX 321~
        ///N4*SOMEWHEREELSE*MN*54321~
        ///LX*1~
        ///CLP*93 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Remit {
            get {
                return ResourceManager.GetString("Remit", resourceCulture);
            }
        }
    }
}
